#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 19 09:29:11 2025

@author: benjamin
"""

# ---- Import Libraries ----
import os
import numpy as np
import Sofa
import SofaRuntime
from stlib3.scene import Scene
from splib3.animation import animate
import Geometries.Constants1 as Const
import rigidification  
import Sofa.Core
import Sofa.constants.Key as Key
from scipy.spatial.transform import Rotation as R 
import h5py 



# ---- Directory Paths ----
dirPath = os.path.dirname(os.path.abspath(__file__)) + '/'
path = os.path.dirname(os.path.abspath(__file__))+'/Meshes/'
MeshesPath = os.path.dirname(os.path.abspath(__file__))+'/Geometries/'
GeneratedMeshesPath = os.path.dirname(os.path.abspath(__file__))+'/Geometries/'

TempPath = os.path.dirname(os.path.abspath(__file__))+'/Temp/'


EdgeMargin = 0.1 *1e-3 

# --- right BoxROI para el borde derecho ---
BoxROIFixCoords = [
    Const.MagneticSkinLength / 2 + Const.BoxTolerance, 
    Const.MagneticSkinWidth  / 2 + Const.BoxTolerance, 
    Const.MagneticSkinHeight  + Const.BoxTolerance,  
    Const.MagneticSkinLength / 2 - EdgeMargin,       
    -(Const.MagneticSkinWidth / 2 + Const.BoxTolerance),
    - Const.BoxTolerance 
    ]

# --- left BoxROI ---
BoxROIFixCoords1 = [
    -(Const.MagneticSkinLength / 2 - EdgeMargin),           
    Const.MagneticSkinWidth  / 2 + Const.BoxTolerance,   
    Const.MagneticSkinHeight + Const.BoxTolerance,       
    -(Const.MagneticSkinLength / 2 + Const.BoxTolerance),
    -(Const.MagneticSkinWidth / 2 + Const.BoxTolerance), 
    -Const.BoxTolerance     
    ]



def calculate_B_field(distance_r_m, magnetic_moment_direction, mu_magnitude):
    """
    Calculates the magnetic field B generated by a magnetic dipole at a given point.

    Parameters:
    - distance_r_mm: Vector (in mm) from the dipole to the point where the field is measured.
    - magnetic_moment_direction: Unit vector indicating the direction of the magnetic moment.
    - mu_magnitude: Magnitude of the magnetic moment (e.g., in A·m²).

    Returns:
    - B_field_pT: Magnetic field vector at the point, in picoTesla (pT).
    """

    # Convert the distance vector to an array and compute its norm
    r = np.array(distance_r_m)  

    r_magnitude = np.linalg.norm(r) 
          
    # print('r_magnitude', r_magnitude)
    # Unit vector in the direction of r
    r_hat = r / r_magnitude
    # print('rhat', r_hat)
    Mu_hat = magnetic_moment_direction
    # Full magnetic moment vector (direction * magnitude)
    mu = [x * mu_magnitude for x in Mu_hat]

    # Compute the dipole field tensor: 3*r̂*r̂ᵀ - I
    tensor = 3 * np.outer(r_hat, r_hat) - np.identity(3)

    # Apply the formula: B = (μ₀ / 4π) * (tensor ⋅ μ) / |r|³
    numerator = np.matmul(tensor, mu)
    denominator = 4 * np.pi * (abs(r_magnitude)**3)

    # Magnetic field B in Tesla
    B_field = numerator / denominator

    # Convert Tesla to microTesla (1e6) or miliTesla (1e3)
    B_field_pT = B_field * 1e6   # 1000000000000000 
    # print('B_field_pT', B_field_pT)
    return B_field_pT



def generate_contact_points(MagnetPosition, z_target):
    contact_points = []

    dist_x = MagnetPosition[0,0].max() - MagnetPosition[1,0].min()  
    dist_y = MagnetPosition[0,1].max() - MagnetPosition[5,1].min()

    print('dist_x', dist_x)
    print('dist_y', dist_y)

    for magnet in MagnetPosition:
        cx, cy = magnet[0], magnet[1]
 
        points = [
            [cx, cy, z_target],                    # centro
            [cx - dist_x, cy + dist_y, z_target],  # NW
            [cx + dist_x, cy + dist_y, z_target],  # NE
            [cx - dist_x, cy - dist_y, z_target],  # SW
            [cx + dist_x, cy - dist_y, z_target],  # SE
        ]
        contact_points.extend(points)


    return contact_points, len(contact_points)  
   

def print_h5_structure(filename):
    def print_attrs(name, obj):
        if isinstance(obj, h5py.Dataset):
            print(f"[DATASET] {name}  shape={obj.shape}  dtype={obj.dtype}")
        elif isinstance(obj, h5py.Group):
            print(f"[GROUP]   {name}")

    with h5py.File(filename, "r") as f:
        print("=== ESTRUCTURA DEL ARCHIVO HDF5 ===")
        f.visititems(print_attrs)




class Controller(Sofa.Core.Controller):   
    
    def __init__(self, *args, **kwargs):
        Sofa.Core.Controller.__init__(self, *args, **kwargs)
        print(" Python::__init__::" + str(self.name.value))

        # ----- SOFA nodes and objects -----
        self.RootNode = kwargs['RootNode']
        self.RigidMO = kwargs['RigidMO']
        self.CFF = kwargs['CFF']
        self.CFFSphereROI = kwargs['CFFSphereROI'] 
        self.CFFMO = kwargs['CFFMO']   

        # ----- Time and PID variables -----
        self.t = 0
        self.dt = 0.01
        self.time = 0
        self.Kp, self.Ki, self.Kd = 0.5, 10000,0.001
        self.integral_vec = np.zeros(3)
        self.prev_error_vec = np.zeros(3)

        #Data
        self.data_Force = []
        self.data_MagnetPose = []
        self.data_SensorPose = []
        self.data_MagneticField = []
        self.data_IdenterPosition = []
        self.data_setpoint = []
        # self.index_secuences = []

        # self.tiempo_activo = 0
        self.idx_trayectory = 0
        self.last_force_idx = -1  


        self.wait_counter = 0 
        self.frames_to_wait = 0.1
        self.just_changed_force = False
        self.waiting = False
        self.quadrant_real = None
        self.forces_real = None


        self.current_point =  0
        self.current_force_idx = 0
        self.force_wait_counter = 0

    

    # def save_to_h5(self):
    #     # os.makedirs("Results", exist_ok=True)  _strecht_20 
    #     filename = "sim_experiment_force_0.0to3.0N_step0.1N_single_test50_stretch_000pct.h5" 
    #     filename = os.path.join("Results", filename)

    #     with h5py.File(filename, 'w') as f:
    #         # f.create_dataset('MagnetPose', data=np.array(self.data_MagnetPose))
    #         # f.create_dataset('SensorPose', data=np.array(self.data_SensorPose))
    #         f.create_dataset('forcesTest', data=np.array(self.data_Force))
    #         f.create_dataset('MagneticField', data=np.array(self.data_MagneticField ))
    #         f.create_dataset('IdenterPosition', data=np.array(self.data_IdenterPosition ))
    #         f.create_dataset('index_sequences', data=np.array(self.index_sequences ))

    #     print(f"Datos guardados en {filename}")



    def save_to_h5(self):

        filename = os.path.join("Results", "sim_experiment_force_0.0to3.0N_step0.1N_single_test50_stretch_000pct.h5")

        with h5py.File(filename, 'w') as f:

            grp = f.create_group("presses")
            
            # Lists to collect all data for top-level datasets
            all_forces = []
            all_stretchmagtec = []
            all_positions = []
            all_timestamps = []
            all_labels = []
            
            # Track cumulative index for start_idx/end_idx calculation
            cumulative_idx = 0

            for press_id in range(len(self.quadrant_real)):
                g = grp.create_group(f"press_{press_id:03d}")

                # Get data for this press
                forces_3d = np.array(self.data_Force[press_id])  # [samples, 3] (Fx, Fy, Fz)
                magtec = np.array(self.data_MagneticField[press_id])  # [samples, 15, 3]
                positions = np.array(self.data_IdenterPosition[press_id])  # [samples, 3]
                
                # Convert forces from 3D to 6D (add Tx=0, Ty=0, Tz=0)
                n_samples = forces_3d.shape[0]
                forces_6d = np.zeros((n_samples, 6), dtype=forces_3d.dtype)
                forces_6d[:, :3] = forces_3d  # Fx, Fy, Fz
                # Tx, Ty, Tz remain zeros (not available in simulation)
                
                # Generate timestamps (assuming 100 Hz sampling rate)
                timestamps = np.arange(n_samples) * 0.01
                
                # Get label (offset) for this press
                quadrant = self.quadrant_real[press_id]
                offset = quadrant if quadrant else "unknown"
                
                # Create label string matching real data format: 'pos_X_offset_press_Y_sequence_Z'
                # For simulation, we use simpler format but compatible
                label_str = f"sim_pos_{press_id:03d}_{offset}_press_0_sequence_0"
                
                # Calculate start and end indices in top-level concatenated dataset
                start_idx = cumulative_idx
                end_idx = cumulative_idx + n_samples - 1
                cumulative_idx += n_samples
                
                # Save per-press datasets
                g.create_dataset("forces", data=forces_6d)
                g.create_dataset("stretchmagtec", data=magtec)
                g.create_dataset("positions", data=positions)
                g.create_dataset("timestamps", data=timestamps)
                
                # Store attributes matching real data structure
                g.attrs["label"] = label_str.encode('utf-8') if isinstance(label_str, str) else label_str
                g.attrs["offset"] = offset.encode('utf-8') if isinstance(offset, str) else offset
                g.attrs["stretch_label"] = b"stretch_000pct"  # Can be made configurable
                g.attrs["stretch_level"] = np.float64(0.0)  # Can be made configurable
                g.attrs["start_idx"] = np.float64(start_idx)
                g.attrs["end_idx"] = np.float64(end_idx)
                
                # Calculate initial_z and max_indentation from positions
                if len(positions) > 0:
                    initial_z = np.float64(positions[0, 2])
                    max_indentation = np.float64(np.min(positions[:, 2]) - positions[0, 2])
                else:
                    initial_z = np.float64(0.0)
                    max_indentation = np.float64(0.0)
                
                g.attrs["initial_z"] = initial_z
                g.attrs["max_indentation"] = max_indentation
                
                # Collect data for top-level datasets
                all_forces.append(forces_6d)
                all_stretchmagtec.append(magtec)
                all_positions.append(positions)
                all_timestamps.append(timestamps)
                all_labels.append([label_str] * n_samples)
            
            # Create top-level concatenated datasets (matching real data structure exactly)
            # These are ALL samples from ALL presses concatenated together
            forces_concat = np.concatenate(all_forces, axis=0)
            stretchmagtec_concat = np.concatenate(all_stretchmagtec, axis=0)
            positions_concat = np.concatenate(all_positions, axis=0)
            timestamps_concat = np.concatenate(all_timestamps, axis=0)
            
            # Save in real data format (for compatibility)
            f.create_dataset("forces", data=forces_concat)
            f.create_dataset("stretchmagtec", data=stretchmagtec_concat)
            f.create_dataset("positions", data=positions_concat)
            f.create_dataset("timestamps", data=timestamps_concat)
            
            # Labels as fixed-length strings (|S64) matching real data format
            labels_flat = [item for sublist in all_labels for item in sublist]
            # Convert to fixed-length string array (64 characters max, matching real data)
            labels_array = np.array([lbl.encode('utf-8')[:64].ljust(64, b'\x00') for lbl in labels_flat], dtype='S64')
            f.create_dataset("labels", data=labels_array)
            
            # ALSO save original simulation-specific datasets (for simulation analysis)
            # forcesTest: original 3D forces (Fx, Fy, Fz only)
            forces_3d_concat = forces_concat[:, :3]  # Extract only Fx, Fy, Fz
            f.create_dataset("forcesTest", data=forces_3d_concat)
            
            # MagneticField: same as stretchmagtec (simulation naming)
            f.create_dataset("MagneticField", data=stretchmagtec_concat)
            
            # IdenterPosition: same as positions (simulation naming)
            f.create_dataset("IdenterPosition", data=positions_concat)

        print("Save data to HDF5")




    def loaddata(self, filename):
        total_samples = 0
        all_quadrants = []
        all_forces = []
        print_h5_structure(filename)


        with h5py.File(filename, 'r') as f:
            presses = f['presses']
            print(f"shape presses: {len(presses)}")

            total_samples_count = sum(f['forces'][()].shape[0] for f in presses.values())
            sample_sequence_index = np.zeros(total_samples_count, dtype=np.int32)



            current_index = 0
            for seq_id, press_key in enumerate(sorted(presses.keys())):
                press = presses[press_key]

                forces = press['forces'][:]  # [samples, 6]
                fz = forces[:, 2]  # Extract Fz component (force in Z direction)
                # timestamps = press['timestamps'][:]  
                # magnteic_field_B = press["stretchmagtec"][:]     # shape = [samples, 15, 3]

                n_samples = fz.shape[0]

                 # Asignar secuencia a cada muestra
                sample_sequence_index[current_index : current_index + n_samples] = seq_id
                current_index += n_samples
                total_samples += n_samples

                label = press.attrs.get("label", "").decode() if isinstance(press.attrs.get("label", ""), bytes) else press.attrs.get("label", "")
                quadrant = None

                if label:
                    quadrants = ["center", "ne", "nw", "se", "sw"]
                    quadrant = next((q for q in quadrants if f"_{q}_" in label), None)
                    # print(f"Quadrant: {quadrant}")
                    # print(f"Force: {fz}")
                all_quadrants.append(quadrant)
                all_forces.append(fz)

            num_presses = len(f["presses"])
            print(f"Total samples loaded: {total_samples} from {num_presses} presses.")


        return all_quadrants, all_forces, sample_sequence_index
    
    def quadrant_to_index(self, q):
        mapping = {
            "center": 0,
            "nw": 1,
            "ne": 2,
            "se": 3,
            "sw": 4,
        }
        return mapping.get(q, None)             

    def set_z(self, p, z):
            p = np.array(p, dtype=float)
            p[2] = z
            return p

    def MoveCFFSphereROI(self, pos):   
        self.CFFSphereROI.centers = [pos.tolist()]
        
    def onAnimateBeginEvent(self, event):
          
        roi_indices = self.CFFSphereROI.indices.value
        n_roi_indices = len(roi_indices)

        #strecht 
        if self.t == 0:  
            displacement = -0.00  # in meters
            grab_node = self.RootNode.ExternalRefNode
            grab = grab_node.getObject('ExternalMO')
            if grab is None:
                return
            currentValue = list(grab.translation.value)
            currentValue[0] = displacement
            grab.translation.value = currentValue
            grab.reinit()

            #load data
            quadrant_real, forces_real, sample_index= self.loaddata("/home/benjamin/Repos/Mag_Tec_Models/data/Single_Point/force_0.0to3.0N_step0.1N_single_test50/cleaned/data/test_50_000_cleaned.h5")
            # quadrant_real, forces_real, sample_index= self.loaddata("/home/benjamin/Repos/MagTecSkinSofa/Scenes/Results/test_data/sim_experiment_force_0.0to3.0N_step0.1N_single_test50_stretch_000pct.h5")    
            
            self.quadrant_real = quadrant_real   
            self.forces_real = forces_real
            self.index_sequences = np.array(sample_index)
    

        base_roi = self.RootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('BaseFixROI')
        indices = base_roi.indices.value
        tetras = self.RootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model.getObject('tetras')
        positions = tetras.position.value
         
        cff_sphere = self.CFFSphereROI
        cff_sphere.findData('position').value = tetras.position.value
        cff_sphere.reinit()

        

        #Para que los puntos lleguen a la posicion final 
        if self.t == 30:

            positions = np.array(tetras.position.value)
            # rest_positions[indices] = positions[indices]
            # base_positions = [positions[i] for i in indices]
            base_positions = positions[indices]
            # print("Posiciones actuales:", base_positions)
            # tetras.rest_position.value = rest_positions.tolist()

            base_node = self.RootNode.ExternalRefNodeBase
            base = base_node.getObject('ExternalBaseMO')
            # print('base.position.value', base.position.value)
            
            base.position.value = base_positions.tolist()
            # print('base.position.value', base.position.value) 
            base.reinit()

            model_spring = self.RootNode.solverNode.RigidNode.RigidifiedNode.deformableNode.model
            spring = model_spring.getObject('BaseFixSpring')
            # print('spring', spring.findData('stiffness').value)
            spring.findData('stiffness').value = [1e12]

            #sensor del medio 
            MagnetPose = self.RigidMO.position.value[0:Const.NMagnets, :]
            # ---- Extract 3D positions of magnets----
            MagnetPosition = MagnetPose[:, :3]
            z_target = Const.MagneticSkinHeight

            indice_medio = int((len(MagnetPosition)-1)/2)
            punto_medio = MagnetPosition[indice_medio]
    
            #En x
            magnet_left = MagnetPosition[indice_medio - 1]
            magnet_right = MagnetPosition[indice_medio + 1]
            magnet_up = MagnetPosition[indice_medio + 5]
            magnet_down = MagnetPosition[indice_medio - 5]

            # Superiores/ Inferiores
            punto_sup_izq = (magnet_up  + magnet_left) / 2
            punto_sup_der = (magnet_up  + magnet_right) / 2
            punto_inf_izq = (magnet_down + magnet_left) / 2
            punto_inf_der = (magnet_down + magnet_right) / 2

            
            punto_medio = self.set_z(punto_medio, z_target)      #center    
            punto_sup_izq = self.set_z(punto_sup_izq, z_target)  #nw          
            punto_sup_der = self.set_z(punto_sup_der, z_target)  #ne
            punto_inf_izq = self.set_z(punto_inf_izq, z_target)  #sw
            punto_inf_der = self.set_z(punto_inf_der, z_target)  #se  



            self.trayectoria_5puntos= np.array([punto_medio, punto_sup_izq, punto_sup_der, punto_inf_der, punto_inf_izq])
            # 0 = center # 1 = nw   # 2 = ne # 3 = se # 4 = sw    



        # force_idx =  [0, 0, 0]
        identer_position = [0, 0, 0]
        idx = -1

        if self.t > 30:

            quadrant = self.quadrant_real[self.current_point]
            index_quadrant = self.quadrant_to_index(quadrant)

            identer_position  = np.array(self.trayectoria_5puntos[index_quadrant]).flatten()
            self.MoveCFFSphereROI(identer_position)

            force_per_point = self.forces_real[self.current_point]
            current_force = force_per_point[self.current_force_idx]
            force_idx = np.array([0, 0, current_force])

            self.CFF.totalForce.value = force_idx
            # print(f"[t={self.t}] fuerza_idx = {self.current_force_idx}, fuerza = {current_force}")


            # ----------- CONTROL DE CAMBIO DE FUERZA ------------
            self.force_wait_counter += 1

            if self.force_wait_counter >= self.frames_to_wait:

                self.force_wait_counter = 0
                self.current_force_idx += 1

                # Activar espera para almacenar datos
                self.waiting = True
                self.frames_counter = 0

                # Pasar al siguiente punto si se acabaron las fuerzas
                if self.current_force_idx >= len(force_per_point):
                    self.current_force_idx = 0
                    self.current_point += 1

                    if self.current_point >= len(self.quadrant_real):
                        print("Terminaron todos los puntos, guardando archivo…")
                        self.save_to_h5()
                        self.current_point = 0




        # ---- Extract pose of magnets and sensors ----
        MagnetPose = self.RigidMO.position.value[0:Const.NMagnets, :]
        SensorPose = self.RigidMO.position.value[Const.NMagnets:, :]

        # ---- Extract 3D positions of magnets and sensors ----
        MagnetPosition = MagnetPose[:, :3]
        SensorPosition = SensorPose[:,:3]

        GlobalMagneticField = []


        for j in range(Const.NSensors):
            
            LocalMagneticField = []
            # print(f'Distancia sensor {j} - imanes:', Dist_Sensor)
            quat_sensor = SensorPose[j, 3:7]
            MiR_Sensor = R.from_quat(quat_sensor)

            R_sensor_inv = R.from_quat(quat_sensor).inv()
            rotation_matrix_sensor_inv = R_sensor_inv.as_matrix()
            # rotation_Matrix_Sensor = MiR_Sensor.as_matrix()

            for i in range(Const.NMagnets):
                Dist_Sensor_global = SensorPosition[j] - MagnetPosition[i]
        #         # pos_iman = Lista_imanes[i]
                
                delta_local = rotation_matrix_sensor_inv @ Dist_Sensor_global           
        #       # print(f'Distancia sensor {j} a {i} - imanes:', delta_local)
                quat_Magnet = MagnetPose[i, 3:7]             
                # print(f"i : {i}, quat_iman{quat_Magnet} ")
                MiR_Magnet = R.from_quat(quat_Magnet)  # (x, y, z, w)               
                rotation_Matrix_Magnet = MiR_Magnet.as_matrix() 
                rotation_Matrix = MiR_Sensor.inv().as_matrix() @ rotation_Matrix_Magnet
                Direccion_momento_magnetico = rotation_Matrix[:, 2]
                
                # print(f"Direccion momento magnetico iman {i+1} ", Direccion_momento_magnetico)

                LocalMagneticField.append(calculate_B_field(delta_local, Direccion_momento_magnetico, Const.mu_magnitude))

            TotalMagneticField = np.sum(LocalMagneticField, axis=0)
            GlobalMagneticField.append(TotalMagneticField)
            

        GlobalMagneticField = np.array(GlobalMagneticField) #(15, 3)



        if self.waiting:
                self.frames_counter += 1

                if self.frames_counter >= self.frames_to_wait:


                    if len(self.data_MagneticField) <= self.current_point:
                        self.data_MagneticField.append([])
                        self.data_Force.append([])
                        self.data_IdenterPosition.append([])

                    self.data_MagneticField[self.current_point].append(GlobalMagneticField)
                    self.data_Force[self.current_point].append(force_idx)
                    self.data_IdenterPosition[self.current_point].append(identer_position)

                    # self.data_MagneticField.append(GlobalMagneticField)
                    # self.data_Force.append(force_idx)
                    # self.data_IdenterPosition.append(identer_position)

                    print(f"[Guardado] Force={force_idx}, press={len(self.data_Force)}")
                    # print(f"[Guardado] MagneticField={GlobalMagneticField}")

                    self.waiting = False
        self.t += 1

        # print(f"GlobalMagneticField shape: {np.shape(GlobalMagneticField)}")

        # Detectar cambio de fuerza


        # if self.current_force_idx != self.last_force_idx:
        #     self.waiting = True
        #     self.frames_counter = 0        # reinicia contador de frames para espera
        #     self.last_force_idx = self.current_force_idx
        # # actualizar último índice

        # # # Si estamos esperando después del cambio de fuerza
        # if self.waiting :
        #     # print(f'setpoints_force[idx]=   {setpoints_force[idx]}')
        #     self.frames_counter += 1

        #     # Esperar N frames (por ejemplo 8)
        #     if self.frames_counter >= self.frames_to_wait:
        #         # Guardar datos AHORA que ya se estabilizó
        #         self.data_MagneticField.append(GlobalMagneticField)
        #         self.data_Force.append(force_idx)
        #         self.data_IdenterPosition.append(identer_position)

        #         print(f"[Iter {self.t:05d}] Guardando datos:")
        #         print(f"  idx fuerza: {idx}")
        #         print(f"  Fuerza aplicada: { force_idx}")
        #         print(f"  Campo magnético (frame actual): {GlobalMagneticField}")
        #         print(f"  Número total de muestras guardadas: {len(self.data_Force)}")
        #         print("-------------------------------------------")

        #         # Apagar la espera
        #         self.waiting = False



def createScene(rootNode):
                
    rootNode.addObject('RequiredPlugin', pluginName='SofaPython3 SoftRobots SoftRobots.Inverse')
    rootNode.addObject('VisualStyle', displayFlags='hideWireframe showBehaviorModels hideCollisionModels hideBoundingCollisionModels showForceFields showInteractionForceFields')
    rootNode.findData('gravity').value = [0, 0, -000] 
    rootNode.findData('dt').value = 0.02

    rootNode.addObject('FreeMotionAnimationLoop')
    rootNode.addObject('QPInverseProblemSolver', printLog='0', epsilon="1e-1", maxIterations="1000", tolerance="1e-5")
    #rootNode.addObject('QPInverseProblemSolver', printLog=False, epsilon="0.0001", maxIterations="1000", tolerance="1e-5")

    rootNode.addObject('GenericConstraintSolver', tolerance="1e-12", maxIterations="10000")

    #rootNode.addObject('BackgroundSetting', color='0 0.168627 0.211765')
    # rootNode.addObject('BackgroundSetting', color='0.85 0.85 0.85')
    rootNode.addObject('BackgroundSetting', color='1  1  1')
    
    
    rootNode.addObject('LightManager')
    rootNode.addObject(
        "PositionalLight",
        name="light1",
        color="0.8 0.8 0.8",
        position=[0, 0, 15*1e-3],
    )
    rootNode.addObject(
        "PositionalLight",
        name="light2",
        color="0.8 0.8 0.8",
        position=[0, 0, -15*1e-3],
    )
    

    # rootNode.addObject()
    # ---- Paths to mesh files ----   
    VolumetricMeshPath = GeneratedMeshesPath + 'MagneticSkin.vtk'
    
    SurfaceMeshPath = GeneratedMeshesPath + 'MagneticSkin.stl'
    
    
    # rootNode.addObject(SinusoidalController(node=rootNode, RigidMO = RigidMO))
    # rootNode.addObject(FixedController(rootNode))

    #----------------------
    # Goal Node
    #---------------------- 
 
    #----------------------
    # Rigidification - start
    #----------------------          
                   
    completeMesh = rootNode.addChild('completeMesh')
    completeMesh.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)
    completeMesh.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    completeMesh.init()
    MeshTetra = completeMesh.addObject('MeshTopology', name="AllMesh", src='@loader')

    

    #---- Create BoxROIs ----
    Boxes = []
    for i in range(len(Const.rigidObjectsBoxCoords[1:])):
        boxTip = completeMesh.addObject('BoxROI', name='Tip'+str(i), box=[Const.rigidObjectsBoxCoords[i+1]], drawBoxes=False, tetrahedra="@container.tetrahedra" , position="@container.position")
        Boxes.append(boxTip)
        boxTip.init()
      
    positionAllPoints = MeshTetra.findData('position').value;
    nbPoints = len(positionAllPoints)
    
    
    IndicesWithRigidIdx = np.empty((0,2), dtype=int)
    
    for (i,Box) in enumerate(Boxes):
        IndicesNP = np.array(Box.indices.value, dtype=int)
        NPoints = len(IndicesNP)
        RigidIdx = np.ones(NPoints,dtype=int)*i
        CurrentIndicesWithRigidIdx = np.append(IndicesNP.reshape((NPoints,1)), RigidIdx.reshape((NPoints,1)),1)
        IndicesWithRigidIdx = np.append(IndicesWithRigidIdx, CurrentIndicesWithRigidIdx,0)
    

    IndicesWithRigidIdxSorted = np.sort(IndicesWithRigidIdx[:,0],0)
    SortedIdxs = np.argsort(IndicesWithRigidIdx[:,0],0)
    SortedRigidIdxs = IndicesWithRigidIdx[:,1][SortedIdxs]
    indicesTip = IndicesWithRigidIdxSorted.tolist()
    rigidBlocks = [IndicesWithRigidIdxSorted.tolist()] 
    
    DeformableIndicesTotal = []    
    
    for i in range(nbPoints):
        if i not in indicesTip:
            DeformableIndicesTotal.append(i)                                 

    freeBlocks = np.sort(DeformableIndicesTotal)    
    IdxsOrderedFreeBlocks = np.argsort(DeformableIndicesTotal)    
    indexPairs = np.array(rigidification.fillIndexPairs(nbPoints,freeBlocks,rigidBlocks))
    NPPointsDeformable = positionAllPoints[DeformableIndicesTotal,:]   
    NPSortedPointsDeformable = NPPointsDeformable[IdxsOrderedFreeBlocks, :]
    PointsDeformable = NPSortedPointsDeformable.flatten().tolist()
    pointsBody = PointsDeformable
    #deformablePoints = pointsBody
       
    pointsTip = np.array(positionAllPoints[indicesTip,:]).flatten().tolist()                                                 
    rigidIndexPerPoint = SortedRigidIdxs.tolist()


    
    solverNode = rootNode.addChild("solverNode")
    solverNode.addObject('EulerImplicitSolver',rayleighStiffness="0.1", rayleighMass="0.1")
    solverNode.addObject('SparseLDLSolver',name='preconditioner')
    solverNode.addObject('GenericConstraintCorrection', linearSolver='@preconditioner')


    RigidNode= solverNode.addChild('RigidNode')
     
    
    nominal_pose = [] 
    TipOrientation = [0, 0, 0, 1]       
    
    
    for center in Const.rigidObjects[1:]:
        CurrentPose = center + TipOrientation
        nominal_pose += CurrentPose
    RigidMO = RigidNode.addObject("MechanicalObject",template="Rigid3d",name="RigidMesh", position=nominal_pose, 
                                  showObject=True, showObjectScale=1.4*1e-3, showIndices=True) # orientation is 240 deg away from scene origin

        #Add the sensors 
    # nominalPoseSensors = [] 
    # TipOrientation = [0, 0, 0, 1]
    # for center in Const.SensorCenters:
    #     center[0] = 0
    #     center[1] = 0
    #     CurrentPose = center + TipOrientation
    #     CurrentPose[3] = 0
    #     nominalPoseSensors  += CurrentPose
    
    # sensorCenter = RigidNode.addChild("sensorCenter")
    # SensorMO = sensorCenter.addObject("MechanicalObject", name="dofs", template="Rigid3",
    #                      position=nominalPoseSensors,
    #                      showObject=True, showObjectScale=1.5*1e-3, showIndices=True, showIndicesScale=0.02*1e-3)
    # # sensorCenter.addObject("UniformMass", totalMass=0.000000001)
    
    # # quiero seguir la posicion de los rigidmesh
    # # sensorIndexPerPoint = [0, 1, 2,3, 4, 5]
    # sensorIndexPerPoint = list(range(Const.NSensors))
    # sensorCenter.addObject("RigidMapping", input="@../RigidMesh", rigidIndexPerPoint=sensorIndexPerPoint )

    # sensorCenter.addObject("EulerImplicitSolver")
    # sensorCenter.addObject("SparseLDLSolver")


    RigidifiedNode =  RigidNode.addChild('RigidifiedNode')   
    RigidifiedNode.addObject('MechanicalObject', name='RigidifiedMesh', position=pointsTip,
                             template='Vec3d', showObject=True, showObjectScale=4*1e-3, showColor=1)       
    RigidifiedNode.addObject("RigidMapping", globalToLocalCoords="true", rigidIndexPerPoint=rigidIndexPerPoint)
    

    # ---- Deformable Node -----
    deformableNode = RigidifiedNode.addChild("deformableNode")
    deformableNode.addObject('PointSetTopologyContainer', position=pointsBody)
    deformableNode.addObject('MechanicalObject', name='DeformableMech', showObject = False, showObjectScale = 4*1e-3)
    # deformableNode.addObject('BarycentricMapping', input='@model/tetras', output='@DeformableMech')
    

    model = deformableNode.addChild('model')
    RigidifiedNode.addChild(model)
    

    	#---- Heart ----
    model.addObject('EulerImplicitSolver', name='nodesolver')          
    model.addObject('ShewchukPCGLinearSolver', iterations='15', name='linearsolver', tolerance='1e-5', update_step='1')
    model.addObject('MeshVTKLoader', name='loader', filename=VolumetricMeshPath)
    model.addObject('TetrahedronSetTopologyContainer', src='@loader', name='container')
    model.addObject('MechanicalObject', name='tetras', template='Vec3', showIndices=False, showIndicesScale='4e-5', rx='0', dz='0')
    model.addObject('UniformMass', totalMass='0.09')
    model.addObject('TetrahedronFEMForceField', template='Vec3', name='FEM', method='large', poissonRatio=Const.PoissonRatio,  youngModulus=Const.YoungsModulus) 
    #CAJA PART1              
    model.addObject('BoxROI', name='BaseROI', box=BoxROIFixCoords, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")              
    model.addObject('RestShapeSpringsForceField', points='@BaseROI.indices', stiffness='1e12')              
    model.addObject("SubsetMultiMapping",name="subsetMapping",template="Vec3d,Vec3d", input='@'+deformableNode.getPathName()+'/DeformableMech' + ' ' + '@'+RigidifiedNode.getPathName()+'/RigidifiedMesh' , output='@./tetras', indexPairs=indexPairs.tolist())
    #Parte que se mueve para estirar
    model.addObject('BoxROI', name='EndROI', box=BoxROIFixCoords1, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")              
    model.addObject('RestShapeSpringsForceField', points='@EndROI.indices', stiffness='1e12', external_rest_shape="@ExternalRefNode/ExternalMO")              

    #Parte de la Base Fija
    model.addObject('BoxROI', name='BaseFixROI', box=Const.BoxROIFixCoords, drawBoxes=True, position="@tetras.rest_position", tetrahedra="@container.tetrahedra")            
    model.addObject('RestShapeSpringsForceField', name='BaseFixSpring' , points='@BaseFixROI.indices', stiffness='0', external_rest_shape="@ExternalRefNodeBase/ExternalBaseMO")
    # Fija solo en Y y Z (libre en X)
    # model.addObject('PartialFixedProjectiveConstraint',
    #                 name='BasePartialFix',
    #                 indices='@BaseROI.indices',
    #                 fixedDirections=[0, 1, 1],   # libre en X, fijo en Y y Z
    #                 # projectVelocity=True,
    #                 showObject=True,
    #                 drawSize=0.0000002)
    # ----------------------------------------
    # Visualization                          
    # ----------------------------------------
    
    modelVisu = model.addChild('visu')
    modelVisu.addObject('MeshSTLLoader', filename=SurfaceMeshPath, name="loader")
    modelVisu.addObject('OglModel', src="@loader", scale3d=[1, 1, 1])
    modelVisu.addObject('BarycentricMapping')
    
    #Parte que se mueve
    ExternalRefNode = rootNode.addChild("ExternalRefNode")
    ExternalRefNode.addObject('MechanicalObject', name='ExternalMO', template='Vec3', showObject=True, showObjectScale=15*1e-3, showColor = [0,0,.7],
                   showIndices=False, showIndicesScale=4e-5,
                   position='@../solverNode/RigidNode/RigidifiedNode/deformableNode/model/EndROI.pointsInROI')

    #Parte para fijar la base 
    ExternalRefNodeBase = rootNode.addChild("ExternalRefNodeBase")
    ExternalRefNodeBase.addObject('MechanicalObject', name='ExternalBaseMO', template='Vec3', showObject=True, showObjectScale=4, showColor = [0,0,.7],
                   showIndices=False, showIndicesScale=4e-5,
                   position='@../solverNode/RigidNode/RigidifiedNode/deformableNode/model/BaseFixROI.pointsInROI')
    



        
    	#---- Sphere ROI ---- 
    CFFNode = model.addChild('CFFNode')
    CFFNode.addObject('MeshSTLLoader', filename=SurfaceMeshPath, name="loader")
    # CFFMO = CFFNode.addObject('MechanicalObject', position='@loader.position') 
    # # trayectoria_points = S_trajectory(np.array(Const.MagnetCenters)[:, :2])
    # CFFSphereROI = CFFNode.addObject('SphereROI', template="Vec3d", name='CFFSphereROI', centers=[0,0,3*1e-3], radii=[Const.indenterRadius], position='@CFFMO.position', drawSphere=True)
    # # CFFSphereROI.init()              
    # CFF = CFFNode.addObject('ConstantForceField', name='CFF', template='Vec3', indices='@CFFSphereROI.indices', totalForce=[0, 0, 0])                               
    # # CFFNode.addObject("BarycentricMapping")
    # CFFNode.addObject('BarycentricMapping', input='@../tetras', output='@CFFMO')
    
    CFFMO = CFFNode.addObject('MechanicalObject', position='@../tetras.position')
    CFFSphereROI = CFFNode.addObject('SphereROI', template="Vec3d", name='CFFSphereROI', centers=[0,0,3*1e-3], radii=[Const.indenterRadius], position='@../tetras.position', drawSphere=True)
    CFF = CFFNode.addObject('ConstantForceField', name='CFF', template='Vec3', indices='@CFFSphereROI.indices', totalForce=[0, 0, 0], showArrowSize='0.02*1e-3')
    CFFNode.addObject("BarycentricMapping")

    rootNode.addObject(Controller(RootNode=rootNode, RigidMO = RigidMO, CFF=CFF, CFFMO=CFFMO, CFFSphereROI=CFFSphereROI ))
    # rootNode.addObject(FixedController(
    #                                     node=rootNode,
    #                                     RigidMO=RigidMO,  
    #                                     displacement=Const.displacement
    #                                 ))